-- SQL Basics : 
CREATE TABLE customers(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

--DROP TABLE customers;

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO customers (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO customers 
VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );

SELECT * FROM customers;

SELECT ID, NAME, SALARY FROM customers;

SELECT ID, NAME, SALARY FROM customers WHERE SALARY > 2000;
SELECT ID, NAME, SALARY FROM customers WHERE NAME = 'Hardik';
SELECT ID, NAME, SALARY FROM customers WHERE SALARY > 2000 AND AGE < 25;
SELECT ID, NAME, SALARY FROM customers WHERE SALARY > 2000 OR AGE < 25;

UPDATE customers set ADDRESS = 'Pune' where ID = 6;
UPDATE customers SET ADDRESS = 'Pune', SALARY = 1000.00;

/*If you want to DELETE ID number 6 in this table*/
DELETE  FROM customers WHERE ID = 6;

/*If you want to DELETE all the records from the CUSTOMERS table*/
DELETE FROM customers;

SELECT * FROM customers WHERE SALARY LIKE '200%';

SELECT TOP 3 * FROM customers;
/* SELECT * FROM customers LIMIT 3; LIMIT : when using MySql server */
/* SELECT * FROM CUSTOMERS WHERE ROWNUM <= 3; ROWNUM : when using Oracle server */

SELECT * FROM customers ORDER BY NAME, SALARY;
SELECT * FROM customers ORDER BY NAME DESC;

SELECT NAME, SUM(SALARY) FROM customers GROUP BY NAME;

SELECT DISTINCT SALARY FROM customers;

SELECT * FROM customers ORDER BY NAME, SALARY;
SELECT * FROM customers ORDER BY NAME DESC;

SELECT * FROM customers
   ORDER BY (CASE ADDRESS
   WHEN 'DELHI' 	 THEN 1
   WHEN 'BHOPAL' 	 THEN 2
   WHEN 'KOTA' 	 THEN 3
   WHEN 'AHMEDABAD' THEN 4
   WHEN 'MP' 	THEN 5
   ELSE 100 END) ASC, ADDRESS DESC;

-- SQL Advanced : 

/*Dropping Constraints*/
ALTER TABLE EMPLOYEES DROP CONSTRAINT EMPLOYEES_PK;
ALTER TABLE EMPLOYEES DROP PRIMARY KEY;

SELECT ID, NAME, AGE, AMOUNT 
FROM CUSTOMERS, ORDERS 
WHERE  CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

SELECT  ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION
SELECT  ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

SELECT  ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION ALL
SELECT  ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

SELECT  ID, NAME, AGE, ADDRESS, SALARY
FROM CUSTOMERS
WHERE SALARY IS NOT NULL;

SELECT  ID, NAME, AGE, ADDRESS, SALARY
FROM CUSTOMERS
WHERE SALARY IS NULL;

SELECT C.ID, C.NAME, C.AGE, O.AMOUNT 
FROM CUSTOMERS AS C, ORDERS AS O
WHERE  C.ID = O.CUSTOMER_ID;

SELECT  ID AS CUSTOMER_ID, NAME AS CUSTOMER_NAME
FROM CUSTOMERS
WHERE SALARY IS NOT NULL;

ALTER TABLE CUSTOMERS ADD SEX char(1);

ALTER TABLE CUSTOMERS DROP SEX;

TRUNCATE TABLE CUSTOMERS;

SELECT * FROM CUSTOMERS;
Empty set (0.00 sec)

CREATE VIEW CUSTOMERS_VIEW AS
SELECT name, age
FROM  CUSTOMERS;

SELECT * FROM CUSTOMERS_VIEW;

CREATE VIEW CUSTOMERS_VIEW AS
SELECT name, age
FROM  CUSTOMERS
WHERE age IS NOT NULL
WITH CHECK OPTION;

UPDATE CUSTOMERS_VIEW
SET AGE = 35
WHERE name = 'Ramesh';

DELETE FROM CUSTOMERS_VIEW WHERE age = 22;

DROP VIEW CUSTOMERS_VIEW;

SELECT ID, NAME, AGE, ADDRESS, SALARY
FROM CUSTOMERS
GROUP BY age
HAVING COUNT(age) >= 2;

DELETE FROM CUSTOMERS
WHERE AGE = 25;
COMMIT;

DELETE FROM CUSTOMERS
WHERE AGE = 25;
ROLLBACK;